apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gke-filestore-pvc
spec:
  accessModes:
  - ReadWriteMany
  stostorageClassName: standard-rwx
  resources:
    requests:
      storage: 100Gi

