apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp-container
        image: stacksimplify/kubenginx:1.0.0
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html/filestore
            name: persistent-storage
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: gke-filstore-pvc
        
